version: 2
updates:
  # 1. Track dependencies in the Client folder
  - package-ecosystem: "npm"
    directory: "/Client"
    schedule:
      interval: "weekly"
    registries:
      - github-packages

  # 2. Track dependencies in the Server folder
  - package-ecosystem: "npm"
    directory: "/Server"
    schedule:
      interval: "weekly"
    registries:
      - github-packages
